apiVersion: v1
kind: Service
metadata:
  name: my-ip
  annotations:
    metallb.io/address-pool: he-global
    metallb.io/loadBalancerIPs: 2001:470:1f13:330:a11b:1b1b:0:19
spec:
  selector:
    app: my-ip
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http3
      port: 443
      targetPort: http3
      protocol: UDP
  
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  sessionAffinity: ClientIP
  trafficDistribution: PreferClose
  externalTrafficPolicy: Local
  